"""Writes SpellIDs.lua: the spell ids /sdi dump all asks the client for, every rank of every
class ability in tests/fixtures/forever_spellbook_all.json.

    python tools/make_spell_ids.py

Run it again whenever tools/build_corpus.py --all has rebuilt the fixture; test_client_texts.lua
fails while the two disagree.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
rows = json.loads((root / "tests/fixtures/forever_spellbook_all.json").read_text(encoding="utf-8"))
ids = sorted({r["id"] for r in rows})

lines = [
    "-- SpellDamageInfo: the spell ids /sdi dump all asks the client for: every rank of every class",
    "-- ability in tests/fixtures/forever_spellbook_all.json. Generated by tools/make_spell_ids.py.",
    "-- Copyright (c) 2026 Ironship. MIT licence, see LICENSE.",
    "",
    "local _, ns = ...",
    "ns = ns or {}",
    "",
    "-- one string, read only when /sdi dump all runs",
    "ns.AllSpellIDs = table.concat({",
]
per_line = 14
for i in range(0, len(ids), per_line):
    lines.append('  "' + ",".join(str(x) for x in ids[i:i + per_line]) + ',",')
lines.append('}, "")')
lines.append("")
(root / "SpellIDs.lua").write_text("\n".join(lines), encoding="utf-8", newline="\n")
print(f"SpellIDs.lua: {len(ids)} ids")
